ttrss:
  image: wangqiru/ttrss:latest
  container_name: ttrss
  # ports:
  #  - "8199:80"
  environment:
    - SELF_URL_PATH=https://98.142.142.133.16clouds.com/ttrss
    - DB_PASS=ttrss
    - DB_HOST=postgres
    - DB_NAME=postgres
    - DB_USER=postgres
    - PUID=1000
    - PGID=1000
  volumes:
    - cache:/var/www/cache/
  links:
    - postgres
      # - mercury
    - rsshub
  stdin_open: true
  tty: true
  restart: always

  # mercury:
  # image: wangqiru/mercury-parser-api:latest
  # container_name: mercury
  # restart: always

postgres:
  image: postgres:16-alpine
  container_name: postgres
  environment:
    - POSTGRES_PASSWORD=ttrss
  volumes:
    - ~/postgres/data/:/var/lib/postgresql/data
  restart: always


# Uncomment the following if you want to enable watchtower
# watchtower:
#   container_name: watchtower
#   image: containrrr/watchtower:latest
#   volumes:
#     - /var/run/docker.sock:/var/run/docker.sock
#   environment:
#     - WATCHTOWER_CLEANUP=true
#     - WATCHTOWER_POLL_INTERVAL=86400
#   restart: always

rsshub:
  container_name: rsshub
  image: diygod/rsshub:latest
  environment:
    - NODE_ENV=production
    - DEBUG_INFO=false
    - LOGGER_LEVEL=info
    - PORT=80
    - NO_LOGFILES=true
  restart: unless-stopped
  expose:
    - 80


