daemon           off;
pid              /run/nginx.pid;
worker_processes auto;

events {
    worker_connections 1024;
}

http {
    include      mime.types;
    default_type application/octet-stream;

    server_tokens     off;
    tcp_nopush        on;
    tcp_nodelay       on;
    sendfile          on;
    keepalive_timeout 65;
    gzip              on;
    gzip_vary         on;
    gzip_min_length   1024;
    gzip_comp_level   5;
    gzip_types        text/css text/javascript application/json application/javascript application/xml application/rss+xml image/svg+xml;

    server {
        listen 80;
        root /var/www;

        index index.php index.html;

        location ~ /\. {
            return 404;
        }

        location / {
            try_files $uri $uri/ =404;
        }

        # https://github.com/tt-rss/tt-rss-plugin-nginx-xaccel
        location ^~ /cache {
            internal;
            expires 30d;
            add_header Cache-Control "public, immutable";
        }
        location ~* \.(js|css|woff2?|svg|png|jpg|jpeg|webp|ico)$ {
            expires 7d;
            add_header Cache-Control "public";
            try_files $uri =404;
        }

        location ~ \.php$ {
            fastcgi_split_path_info ^(.+\.php)(/.+)$;
            fastcgi_pass 127.0.0.1:9000;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_index index.php;
            include fastcgi_params;
        }
        location ~ /plugins\.local/.*/api/.*\.php(/|$) {
            fastcgi_split_path_info ^(.+\.php)(/.+)$;
            set $path_info $fastcgi_path_info;
            fastcgi_param PATH_INFO $path_info;
            fastcgi_pass 127.0.0.1:9000;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_index index.php;
            include fastcgi_params;
        }
    }
}
