name: CI for docs

on:
    pull_request:
        branches: master
    push:
        branches:
            - '*'
            - '!master'

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
        -
            name: Checkout
            uses: actions/checkout@v1
        -
            name: Set up node
            uses: actions/setup-node@v1
            with:
                node-version: '13.x'
        -
            name: Build vuepress docs
            run: npm install && npm run docs:build
